MongoDB:
  host: localhost
  port: 27017
experiment_name:
  adam: adam:L2-batch_size-lr-num_epochs-primary_metric-solver
  sgd: sgd:L2-batch_size-lr-num_epochs-primary_metric-solver
features: '111'
max_evals: 50
project_name: tune_DL
